services:
  lb:
    build:
      context: ./lb
      dockerfile: ../Dockerfile.lb
    ports:
      - "9999:9999"
    volumes:
      - uds-sockets:/sockets
    security_opt:
      - seccomp:unconfined
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10MB"

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    security_opt:
      - seccomp:unconfined
    environment:
      - NPROBE=${NPROBE:-2}
      - NPROBE_RETRY=${NPROBE_RETRY:-16}
      - NPROBE_EXHAUST=${NPROBE_EXHAUST:-32}
      - TP_MIN_WORKERS=${TP_MIN_WORKERS:-150}
    volumes:
      - uds-sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api1.sock"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    security_opt:
      - seccomp:unconfined
    environment:
      - NPROBE=${NPROBE:-2}
      - NPROBE_RETRY=${NPROBE_RETRY:-16}
      - NPROBE_EXHAUST=${NPROBE_EXHAUST:-32}
      - TP_MIN_WORKERS=${TP_MIN_WORKERS:-150}
    volumes:
      - uds-sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api2.sock"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"

volumes:
  uds-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
