FROM alpine:3.21 AS builder
RUN apk add --no-cache curl xz tar
RUN curl -L https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz \
    | tar -xJ -C /opt --strip-components=1
ENV PATH="/opt:$PATH"

WORKDIR /app
COPY . .
RUN zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-musl

FROM scratch
COPY --from=builder /app/zig-out/bin/lb /lb
ENTRYPOINT ["/lb"]
