FROM alpine:edge AS builder
RUN apk add --no-cache zig

WORKDIR /app
COPY . .
RUN zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux-musl

FROM scratch
COPY --from=builder /app/zig-out/bin/lb /lb
ENTRYPOINT ["/lb"]
