services:
  lb:
    image: ghcr.io/yanpitangui/rinha-de-backend-2026-q1-vptree-lb:2db2d19f035f8792b2a0b599dec2ab7f6e2ef00e
    ports:
      - "9999:9999"
    volumes:
      - uds-sockets:/sockets
    cpuset: "0,1,2,3"
    environment:
      - LB_WORKERS=${LB_WORKERS:-2}
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  api1:
    image: ghcr.io/yanpitangui/rinha-de-backend-2026-q1-vptree:2db2d19f035f8792b2a0b599dec2ab7f6e2ef00e
    hostname: api1
    cpuset: "0,1"
    environment:
      - TP_MIN_WORKERS=${TP_MIN_WORKERS:-64}
      - DOTNET_PROCESSOR_COUNT=1
      - SO_BUSY_POLL=${SO_BUSY_POLL:-50}
      - DOTNET_EnableDiagnostics=0
    volumes:
      - uds-sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api1.sock"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 60s
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "170MB"

  api2:
    image: ghcr.io/yanpitangui/rinha-de-backend-2026-q1-vptree:2db2d19f035f8792b2a0b599dec2ab7f6e2ef00e
    hostname: api2
    cpuset: "2,3"
    environment:
      - TP_MIN_WORKERS=${TP_MIN_WORKERS:-64}
      - DOTNET_PROCESSOR_COUNT=1
      - SO_BUSY_POLL=${SO_BUSY_POLL:-50}
      - DOTNET_EnableDiagnostics=0
    volumes:
      - uds-sockets:/sockets
    healthcheck:
      test: ["CMD-SHELL", "test -S /sockets/api2.sock"]
      interval: 2s
      timeout: 3s
      retries: 30
      start_period: 60s
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock: -1
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "170MB"

volumes:
  uds-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
